{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mermaid2svg.fullname" . }}
  {{- if $.Values.serviceMonitor.namespace }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "mermaid2svg.labels" $ | nindent 4 }}
    {{- range $key, $value := $.Values.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
    - port: http
      path: /metrics
      honorLabels: {{ $.Values.serviceMonitor.honorLabels }}
      {{- if $.Values.serviceMonitor.interval }}
      interval: {{ $.Values.serviceMonitor.interval }}
      {{- end }}
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
      {{- if $.Values.serviceMonitor.relabelings }}
      relabelings:
      {{- toYaml $.Values.serviceMonitor.relabelings | nindent 6 }}
      {{- end }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      {{- include "mermaid2svg.selectorLabels" $ | nindent 6 }}
{{- end -}}
